name: "Calico Dir Changed Job"
# If any file change in the Calico path a new build will be triggered
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - calico/**

jobs:
  calico-dir-change-job:
    runs-on: [ ubuntu-latest ]
    steps:
    - uses: actions/checkout@v2
    - name: Run
      working-directory: ./calico
      run: ./setup.sh
