name: "Weavenet Changed Dir Job"
# If any file change in the weavenet path a new build will be triggered
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - weavenet/**

jobs:
  weavenet-changed-dir-job:
    runs-on: [ ubuntu-latest ]
    steps:
    - uses: actions/checkout@v2
    - name: Run
      working-directory: ./weavenet
      run: ./setup.sh
